Update Device object handling and description
camaraproject/DeviceIdentifier pull request #87
Opened 2024-12-05 21:55 UTC by eric-murray

#### What type of PR is this?
* enhancement/feature
* documentation

#### What this PR does / why we need it:
Other APIs passing a Device object do this by passing a separate parameter named `device`, even if that is the only object passed in the request. This PR updates the Device Identifier API to use this pattern. Documentation on identifying the device from the access token is also updated following the current agreement in Commonalities.

#### Which issue(s) this PR fixes:

Fixes # N/A

#### Special notes for reviewers:
None

#### Changelog input

```
 release-note
 - Update Device object handling and description
```

#### Additional documentation 
None

2024-12-20 10:42 UTC, Kevsy commented on code/API_definitions/device-identifier.yaml
>              GENERIC_404_DEVICE_NOT_FOUND:
```suggestion
            GENERIC_404_IDENTIFIER_NOT_FOUND:

```

2024-12-20 11:09 UTC, Kevsy commented on code/API_definitions/device-identifier.yaml
>              GENERIC_404_DEVICE_NOT_FOUND:
```suggestion
            GENERIC_404_IDENTIFIER_NOT_FOUND:

```

2024-12-20 11:09 UTC, Kevsy commented on code/API_definitions/device-identifier.yaml
>                description: Device identifier not found
```suggestion
              description: Some identifier cannot be matched to a device

```

2024-12-20 11:10 UTC, Kevsy commented on code/API_definitions/device-identifier.yaml
> +                message: The supplied device identifier cannot be matched to a device.
```suggestion
                message: Device identifier not found.

```

2024-12-20 11:15 UTC, Kevsy commented on code/API_definitions/device-identifier.yaml
> +            DeviceIdentifiersMismatch:
```suggestion
            GENERIC_422_IDENTIFIER_MISMATCH:

```

2024-12-20 11:15 UTC, Kevsy commented on code/API_definitions/device-identifier.yaml
> +              description: Inconsistency between device identifiers not identifying the same device
```suggestion
              description: Inconsistency between identifiers not pointing to the same device

```

2024-12-20 11:19 UTC, Kevsy commented on code/API_definitions/device-identifier.yaml
>              GENERIC_404_DEVICE_NOT_FOUND:
```suggestion
             GENERIC_404_IDENTIFIER_NOT_FOUND:

```

2024-12-20 11:21 UTC, Kevsy commented on code/API_definitions/device-identifier.yaml
>                  message: Provided device identifiers are not consistent.
```suggestion
                message: Provided identifiers are not consistent.

```

2024-12-20 11:22 UTC, Kevsy commented on code/API_definitions/device-identifier.yaml
> +              description: Service is not available for the identified device
```suggestion
              description: Service not applicable for the provided identifier

```

2024-12-20 11:23 UTC, Kevsy commented on code/API_definitions/device-identifier.yaml
> +              description: Service is not available for the identified device
```suggestion
              description: The service is not available for the provided identifier.

```

2024-12-20 11:25 UTC, Kevsy commented on code/API_definitions/device-identifier.yaml
> +            UnsupportedDeviceIdentifier:
```suggestion
            GENERIC_422_UNSUPPORTED_IDENTIFIER:

```

2024-12-20 11:26 UTC, Kevsy commented on code/API_definitions/device-identifier.yaml
> +            UnsupportedDeviceIdentifier:
```suggestion
            GENERIC_422_UNSUPPORTED_IDENTIFIER:

```

2024-12-20 11:27 UTC, Kevsy commented on code/API_definitions/device-identifier.yaml
> +                message: None of the provided device identifiers is supported by the implementation.
```suggestion
                message: None of the provided identifiers is supported by the implementation.

```

2024-12-20 11:31 UTC, Kevsy commented on code/API_definitions/device-identifier.yaml
> +            UnnecessaryDeviceIdentifier:
```suggestion
            GENERIC_422_UNNECESSARY_IDENTIFIER:

```

2024-12-20 11:32 UTC, Kevsy commented on code/API_definitions/device-identifier.yaml
> +                message: The device is already identified by the access token
```suggestion
                message: An explicit identifier is provided when a device or phone number has already been identified from the access token
```

2024-12-20 11:32 UTC, Kevsy commented on code/API_definitions/device-identifier.yaml
> +            MissingIdentifier:
```suggestion
            GENERIC_422_MISSING_IDENTIFIER:

```

2024-12-20 11:33 UTC, Kevsy commented on code/API_definitions/device-identifier.yaml
> +                message: The device cannot be identified
```suggestion
                message: An identifier is not included in the request and the device or phone number identification cannot be derived from the 3-legged access token

```

2024-12-20 11:35 UTC, Kevsy commented on code/API_definitions/device-identifier.yaml
>      429TooManyRequests:
```suggestion
     Generic429:

```

2024-12-20 11:40 UTC, Kevsy requested changes
Added suggestions inline to match the latest common.yaml changes for the error names/descriptions

2025-01-02 20:47 UTC, eric-murray commented on code/API_definitions/device-identifier.yaml
>              GENERIC_404_DEVICE_NOT_FOUND:
Example names do not need to match those used in the template. I reviewed all the example names, and for this one propose `Device Cannot Be Found`.

2025-01-02 20:48 UTC, eric-murray commented on code/API_definitions/device-identifier.yaml
>                description: Device identifier not found
I propose:
`description: The provided device identifier cannot be matched to a device known to the API provider`

2025-01-02 20:49 UTC, eric-murray commented on code/API_definitions/device-identifier.yaml
> +                message: The supplied device identifier cannot be matched to a device.
The `message` is always anyway just an example. I propose:
`message: The provided device identifier cannot be matched to a device.`

2025-01-02 20:50 UTC, eric-murray commented on code/API_definitions/device-identifier.yaml
> +            DeviceIdentifiersMismatch:
I propose `Device Identifiers Do Not Match:`

2025-01-02 20:52 UTC, eric-murray commented on code/API_definitions/device-identifier.yaml
> +              description: Inconsistency between device identifiers not identifying the same device
`description: Multiple device identifiers provided which do not all identify the same device`

2025-01-02 21:01 UTC, eric-murray commented on code/API_definitions/device-identifier.yaml
> +              description: Service is not available for the identified device
For same reasoning above, I went with `description: Service is not applicable for the identified device`

2025-01-02 21:01 UTC, eric-murray commented on code/API_definitions/device-identifier.yaml
> +            UnsupportedDeviceIdentifier:
`Unsupported Identifier`

2025-01-02 21:04 UTC, eric-murray commented on code/API_definitions/device-identifier.yaml
> +              description: Service is not available for the identified device
`description: The service is not applicable for the identified device`

2025-01-02 21:07 UTC, eric-murray commented on code/API_definitions/device-identifier.yaml
> +            UnnecessaryDeviceIdentifier:
`Unnecessary Identifier`

2025-01-02 21:08 UTC, eric-murray commented on code/API_definitions/device-identifier.yaml
> +                message: The device is already identified by the access token
`message: An explicit identifier has been provided for the device when this is already identified by the access token`

2025-01-02 21:10 UTC, eric-murray commented on code/API_definitions/device-identifier.yaml
> +                message: The device cannot be identified
`message: An identifier is not included in the request and the device cannot be identified from the 3-legged access token`

2025-01-02 21:23 UTC, eric-murray commented on code/API_definitions/device-identifier.yaml
>      429TooManyRequests:
This name is internal to the OAS definition, so no reason to update it. It is not even displayed by the Swagger editor.

There is some debate as to whether 429 errors need to be documented, so this error definition may yet be removed.

2025-01-03 09:26 UTC, eric-murray commented on code/API_definitions/device-identifier.yaml
> +              description: An identifier is not included in the request and the device cannot be identified from the 3-legged access token
```suggestion
              description: An identifier is not included in the request and the device cannot be identified from the 2-legged access token

```

2025-01-03 09:26 UTC, eric-murray commented on code/API_definitions/device-identifier.yaml
> +                message: An identifier is not included in the request and the device cannot be identified from the 3-legged access token
```suggestion
                message: An identifier is not included in the request and the device cannot be identified from the 2-legged access token

```

2025-01-10 16:12 UTC, eric-murray commented
M3 date is 17th January, so this PR needs to be approved and merged before then so that I can create the release candidate.

So, please add any comments you may have before next Wednesday 15th January. Thanks.

2025-01-10 23:26 UTC, AxelNennker requested changes

2025-01-10 23:26 UTC, AxelNennker commented on code/API_definitions/device-identifier.yaml
> +    - If the subject cannot be identified from the access token and the optional `device` object is not included in the request, then the server will return an error with the `422 MISSING_IDENTIFIER`
```suggestion
    - If a two-legged access token is sent and the optional `device` object is not included in the request, then the server will return an error with the `422 MISSING_IDENTIFIER` error code.

```

2025-01-12 21:39 UTC, eric-murray commented on code/API_definitions/device-identifier.yaml
> +    - If the subject cannot be identified from the access token and the optional `device` object is not included in the request, then the server will return an error with the `422 MISSING_IDENTIFIER`
The text is taken from the template in the [API Design Guidelines](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#appendix-a-normative-infodescription-template-for-when-user-identification-can-be-from-either-an-access-token-or-explicit-identifier)

2025-01-13 07:38 UTC, AxelNennker commented
I deleted my comment/suggestion on error handling. Maybe the API Design Guidelines could be clarified.  I wanted to make clear that if a valid three-legged access token is used but still the subject cannot be identified then that is a server error (500) of the authorization server. But that is not a topic of this PR.

2025-01-15 11:55 UTC, Kevsy approved these changes

2025-01-15 12:48 UTC, merged